### ISSUE TITLE
Built on Android but the screen is white

### ISSUE THREAD

**Issue by bobddadoo** [ya7gisa0/Unity-Raindrops#2]
As the title says, when I build on Android, the screen appears white. How can I fix this?

unity version is 2022.3.29f1

No Problem with desktop
![image](https://github.com/yumayanagisawa/Unity-Raindrops/assets/16355956/9b1d5065-b924-4761-af91-9e9366c434e7)

Android build...
![Screenshot_20240701_153026_UnitySample](https://github.com/yumayanagisawa/Unity-Raindrops/assets/16355956/c028861d-f5dc-48f1-9771-3a550665a6e1)

**Comment by yumayanagisawa** [comment]
It's not an issue :)

**Comment by yumayanagisawa** [comment]
You're very welcome to make this shader compatible with Android :)
